import pandas as pd
import numpy as np
from typing import Tuple, List

def create_lags_and_derivatives(df: pd.DataFrame) -> pd.DataFrame:
    """
    Computes derived transition indicators and creates 1-year and 3-year
    temporal lags for modeling time-series momentum.
    """
    df = df.sort_values(by=['country_id', 'year']).copy()

    # 1. Derived Features (Our Derivatives)
    # GDP per capita
    df['gdp_per_capita'] = df['gdp'] / df['population']
    
    # Carbon Intensity of Grid (gCO2 / kWh)
    # Emissions are in Million Tonnes (1e6 * 1e6 g = 1e12 g), Gen is in TWh (1e9 kWh)
    # Intensity = (Emissions * 1e12) / (Gen * 1e9) = (Emissions * 1000) / Gen
    df['carbon_intensity_elec'] = 0.0
    valid_gen = df['electricity_generation'] > 0
    df.loc[valid_gen, 'carbon_intensity_elec'] = (
        df.loc[valid_gen, 'emissions'] * 1000.0
    ) / df.loc[valid_gen, 'electricity_generation']

    # Carbon Intensity of GDP (Tonnes CO2 / USD)
    df['carbon_intensity_gdp'] = df['emissions'] / df['gdp']

    # Energy Intensity of GDP (kWh / USD)
    df['energy_intensity_gdp'] = 0.0
    valid_gdp = df['gdp'] > 0
    df.loc[valid_gdp, 'energy_intensity_gdp'] = (
        df.loc[valid_gdp, 'electricity_generation'] * 1e9
    ) / df.loc[valid_gdp, 'gdp']

    # Fill NaNs generated by zero division
    for col in ['carbon_intensity_elec', 'carbon_intensity_gdp', 'energy_intensity_gdp', 'gdp_per_capita']:
        df[col] = df[col].fillna(0.0)

    # 2. Time-series temporal lag features
    lag_targets = ['electricity_generation', 'emissions', 'renewable_share']
    for col in lag_targets:
        df[f'{col}_lag_1'] = df.groupby('country_id')[col].shift(1)
        df[f'{col}_lag_3'] = df.groupby('country_id')[col].shift(3)

    # Fill lag NaNs using backward fill within country groupings to avoid dropping start years
    for col in lag_targets:
        df[f'{col}_lag_1'] = df.groupby('country_id')[f'{col}_lag_1'].bfill()
        df[f'{col}_lag_3'] = df.groupby('country_id')[f'{col}_lag_3'].bfill()

    # Final backup fill of residual NaNs
    df = df.fillna(0.0)
    return df

def prepare_training_data(
    df: pd.DataFrame, 
    country_id: int, 
    target_col: str
) -> Tuple[pd.DataFrame, pd.Series, pd.DataFrame, pd.Series, List[str]]:
    """
    Splits sequential country data into training (pre-2019) and validation (2019-2024).
    """
    df_country = df[df['country_id'] == country_id].sort_values(by='year').copy()

    features = [
        'year', 'population', 'gdp', 'gdp_per_capita',
        'electricity_generation_lag_1', 'electricity_generation_lag_3',
        'emissions_lag_1', 'emissions_lag_3',
        'renewable_share_lag_1', 'renewable_share_lag_3',
        'ev_sales_share'
    ]

    # Split indices
    df_train = df_country[df_country['year'] < 2019]
    df_val = df_country[(df_country['year'] >= 2019) & (df_country['year'] <= 2024)]

    X_train = df_train[features]
    y_train = df_train[target_col]
    X_val = df_val[features]
    y_val = df_val[target_col]

    return X_train, y_train, X_val, y_val, features
